name: Hourly Hotdeal Crawler

on:
  schedule:
    - cron: '0 * * * *' # 매시간 정시 실행 (UTC 기준)
  workflow_dispatch:      # 수동 실행 버튼 활성화

jobs:
  run-crawler:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install pandas beautifulsoup4 lxml

      - name: Execute script
        env:
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        run: python JHLWAREHOUSE_PKG_1/hotdeal_crawler.py
