name: Hourly Hotdeal Crawler

on:
  schedule:
    # 0분 정각에는 봇이 몰려 차단될 확률이 높으므로 '17분'으로 설정
    - cron: '17 * * * *'
  workflow_dispatch:

jobs:
  run-crawler:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install pandas beautifulsoup4 lxml playwright
          playwright install chromium

      - name: Execute script
        env:
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        # find 명령어를 통해 폴더 깊숙이 있는 hotdeal_crawler.py를 자동으로 찾아 실행합니다.
        run: |
          FILE_PATH=$(find . -name "hotdeal_crawler.py" | head -n 1)
          echo "실행할 파일 경로: $FILE_PATH"
          python "$FILE_PATH"
